### ISSUE TITLE
[bug] Few Bugs in v2

### ISSUE THREAD

**Issue by shivaabhishek07** [WeMakeDevs/wemakedevs#171]
### Header
- The home button redirects to a new tab, which should refresh the page.
- The hackathon button is redirecting to the roadmaps repo. This confuses the user. If there is no Hackathon repo kind of, you can remove the link from there.
- YouTube button redirects to Kunal's YT channel and there is another YT button in the body which is redirecting to WeMakeDev's YT channel, for a better user experience please provide buttons for both of them. 
### Body
- Roadmaps card- `Roadmaps` button is redirecting to Kunal's courses playlist
- In Partner with us, both Contact us and See Partner testimonial buttons are redirecting to the events repo.
### Footer
-  Inn Join our community, both Telegram and Discord buttons are redirecting to the events repo

**Comment by shivaabhishek07** [comment]
I would like to work on all these issues. Please assign it to me!

**Comment by AnuragThePathak** [comment]
@shivaabhishek07 are these not fixed in https://github.com/WeMakeDevs/wemakedevs/pull/160 ?

**Comment by AnuragThePathak** [comment]
And home click opening new tab is fixed by another PR that I merged merged yesterday.

**Comment by shivaabhishek07** [comment]
> @shivaabhishek07 are these not fixed in #160?

Everything got fixed now except for that footer issue.

**Comment by sboy99** [comment]
@AnuragThePathak  I think that opening issue still persist, cause I worked on v1  but v2 is currently active with the same buggy code. Although the link isn't opening in new tab but its targeting the same domain again and again while clicking home, and loading the website every time, you can check on network tab.   
Assign me I will fix it ASAP.
